function spec = f1can_spec()
%F1CAN_SPEC  Message catalogue (mirror of dbc/f1_telemetry.dbc, Intel byte order).
%   Each signal: name, start bit, length, scale, offset, signed.

    sig = @(n, st, len, sc, off, sgn) struct('name', n, 'start', st, 'len', len, ...
                                            'scale', sc, 'offset', off, 'signed', sgn);
    spec = struct('id', {}, 'name', {}, 'dlc', {}, 'signals', {});

    spec(end+1) = struct('id', hex2dec('010'), 'name', 'F1_SessionCtrl', 'dlc', 2, 'signals', ...
        [sig('Command', 0, 8, 1, 0, false), sig('DriverNumber', 8, 8, 1, 0, false)]);

    spec(end+1) = struct('id', hex2dec('101'), 'name', 'F1_CarTelemetry', 'dlc', 8, 'signals', ...
        [sig('Speed', 0, 16, 0.1, 0, false), sig('RPM', 16, 16, 1, 0, false), ...
         sig('Throttle', 32, 8, 1, 0, false), sig('Gear', 40, 4, 1, 0, false), ...
         sig('Brake', 44, 1, 1, 0, false), sig('DRS', 45, 1, 1, 0, false), ...
         sig('AliveCounter', 48, 4, 1, 0, false), sig('CRC8', 56, 8, 1, 0, false)]);

    spec(end+1) = struct('id', hex2dec('102'), 'name', 'F1_LapContext', 'dlc', 8, 'signals', ...
        [sig('DriverNumber', 0, 8, 1, 0, false), sig('LapNumber', 8, 8, 1, 0, false), ...
         sig('LapDistance', 16, 16, 1, 0, false), sig('LapTime', 32, 20, 0.001, 0, false), ...
         sig('AliveCounter', 52, 4, 1, 0, false), sig('CRC8', 56, 8, 1, 0, false)]);

    spec(end+1) = struct('id', hex2dec('103'), 'name', 'F1_Position', 'dlc', 8, 'signals', ...
        [sig('PosX', 0, 16, 0.1, 0, true), sig('PosY', 16, 16, 0.1, 0, true), ...
         sig('PosZ', 32, 12, 0.1, 0, false), sig('AliveCounter', 44, 4, 1, 0, false), ...
         sig('DriverNumber', 48, 8, 1, 0, false), sig('CRC8', 56, 8, 1, 0, false)]);
end
